### ISSUE TITLE
Create schemes manually using Tags

### ISSUE THREAD

**Issue by gabrielacosta** [abelsilva/swaggerwcf#22]
Hi Abel, 

I need to add manually the model scheme for the response. The project do not have a DataContract associated because it is not necessary. I was checking the implementation and I think the Mapper.cs in Support is the one in charge of the retrospection in the object. 

![image](https://cloud.githubusercontent.com/assets/8519425/16442704/bed22caa-3e17-11e6-997a-b496acbc04f1.png)

Currently, the schemes definition in the GetResponseCodes is getting null in my case no DataContract associated. 

![image](https://cloud.githubusercontent.com/assets/8519425/16442746/fa5a6a62-3e17-11e6-8cf9-d473b4afc285.png)

It is possible to add a new tag for Rest to emulate the DataContract and the DataMember or pass the scheme definition as a SwaggerTag?

![image](https://cloud.githubusercontent.com/assets/8519425/16442824/7675a5da-3e18-11e6-9dd9-49f35d31005f.png)

![image](https://cloud.githubusercontent.com/assets/8519425/16442830/8221076c-3e18-11e6-93ac-df2d05626ecc.png)

I think if you guide I can implement that extra tag so, the implementation with REST calls without DataContract can be resolved too. 

Thanks for your help.
Kind regards,
Juan

**Comment by abelsilva** [comment]
But how would you add the model scheme?

**Comment by gabrielacosta** [comment]
I was planning to add a json string in the tag. I think it is possible.

**Comment by abelsilva** [comment]
currently, the execution flow traverses everything and puts all schema classes on a List<>

At the end, they are all converted to schema representation

I'm not seeing a quick and easy way to make it work.

**Comment by gabrielacosta** [comment]
I was thinking do something like this serialize the object and the pass it to the SwaggerTag

```
"{\"registration_ids\":[\"id1\",\"id2\"],\"data\":{\"message\":\"Your message\",\"tickerText\":\"Your ticket\",\"contentTitle\":\"Your content\"}}"
```
For instance like this class, 

![issue8](https://cloud.githubusercontent.com/assets/8519425/16444742/ef52ed00-3e22-11e6-8197-bd30d84bd484.PNG)

Do you think is possible?

**Comment by gabrielacosta** [comment]
But, in my case I don't have a DataContract so the traverse list<null>, so It won't generate the response scheme. 
There is any tag that can change the response scheme?

**Comment by abelsilva** [comment]
There is no tag, that't what I was referring to, I'm not seeing an easy/quick way of doing it.

Because the response schemas are not inside the 'paths' (functions)

The schemas are only generated after all paths are generated.

I can see a possible way of doing it without changing much stuff:
# create a special class (e.g. ManualSchema) with a static list of schemas
# when traversing the functions/paths, if the override schema exists, instead of adding the class to the list of schemas, add a ManualSchema to the list and put the override value in it (if if already exists in the list, find it and add the override schema to the list)
# when generating the schemas, if the class type is ManualSchema, instead of generating, get the override schemas and add them

**Comment by gabrielacosta** [comment]
Thanks Abel, I will check around the way that you suggested.
