### ISSUE TITLE
BodyStyle != WebMessageBodyStyle.Bare issue

### ISSUE THREAD

**Issue by Soruk** [abelsilva/swaggerwcf#6]
Hi Abel,

We wanted to document our WCF RESTFul service with your Swagger WCF, but we encounter the following issue.
When in WebInvoke attribute of operation in our WCF service we set BodyStyle to WebMessageBodyStyle.WrappedRequest (or anything different from Bare), we get Bad Request Error.
We would like to know whether it is possible to make work the SwaggerWCF with this type of body? And how it can be achieved?

Regards,
Aleksander

**Comment by abelsilva** [comment]
Hi Aleksander

Using WebMessageBodyStyle.Wrapped will somehow make the API less RESTful (at least in my point of view), since when you request for example a list of books, you would instead receive a single object (with the list of books wrapped in it).

But technically it is possible, although it would take some work because it means for each method, two new object types would need to be registered with the Swagger API spec (one for the request and another for the response).

Thanks
Abel

**Comment by Soruk** [comment]
Hi Abel,

Thanks for your quick response.

We use the WCF service (hosted by Windows Service) with WebMessageBodyStyle.WrappedRequest and it is consummed by JavaScript. And it works correctly (and even in production environment)
For documentation purposes we wanted to have Swagger-UI documentation in a sample WebSite that has a SVC service (inheriting form the WCF service).
Do you know whether it is easy to modify your code (C# code in SwaggerWcf) or it must be made in the zip file of www folder?

Aleksander

**Comment by abelsilva** [comment]
It should be possible only on C# code, the zip file is the swagger-ui interface (nothing was changed in it).

**Comment by abelsilva** [comment]
closing issue, let me know if you need more information
